"""Public PRISM API for tutorials and downstream analyses."""
__author__ = "Shiguan Mu"
__email__ = "csshiguan_mu@mail.scut.edu.cn"
__version__ = "0.1.0"
from .applications import (
    SMA_PAPER_METABOLITES,
    annotate_sma_paper_metabolites,
    apply_magpie_landmarks_to_msi,
    assign_dopamine_status,
    attach_sma_metadata,
    build_aligned_msi,
    build_full_msi_with_missing,
    build_sma_new_label,
    estimate_magpie_affine,
    greedy_spatial_matching,
    load_imputed_dopamine_predictions,
    load_visium_rna_with_spatial,
    plot_dopamine_distribution,
    plot_magpie_alignment_preview,
    plot_matching_summary_bar,
    plot_pd_human_volcano,
    plot_spatial_overlay,
    prepare_sma_rna,
    run_imputed_dopamine_deg,
    sma_label_table,
    spatial_mapping_table,
    transform_coordinates_affine,
    write_sma_h5ad,
)
from .core import (
    Cal_Spatial_Net,
    Stats_Spatial_Net,
    Transfer_pytorch_Data,
    add_prism_interaction_pca,
    align_cluster_to_reference,
    align_cluster_to_truth,
    apply_interaction_embedding,
    clustering,
    get_domain_label_order,
    get_domain_palette,
    known_domain_presets,
    load_checkpoint_state,
    mclust_R,
    pca,
    register_domain_palette,
    relabel_clusters_for_display,
    rewire_spatial_net,
    search_res,
    select_best_device,
    set_prism_plot_style,
    set_seed,
    show_real_missing,
    simulate_celltype_missing,
    simulate_missing_sliding,
    to_dense,
)
from .models import PRISM, PRISM_DM
from .preprocess import (
    get_missing_indices,
    preprocess_adt,
    preprocess_atac,
    preprocess_metabolomics,
    preprocess_omics,
    preprocess_rna,
    save_raw_layer_and_counts,
)
from .prior import (
    AOTGraphConfig,
    aot_distance_matrix_full,
    build_aot_knn_graph,
    build_modality_context_prior,
    compute_aot,
    compute_covet,
    compute_similarity_prior,
    covet_sqrt_to_aot_features,
    prepare_similarity_subset,
    save_aot_matrix,
    sparse_topk_global,
)
from .training import train_PRISM, train_PRISM_DM
from .validation import (
    compute_metrics_each_pair,
    evaluate,
    evaluate_protein_prediction,
    materialize_prism_raw_imputation,
    plot_imputation_metric_boxplot,
    plot_per_protein_correlations,
    plot_prism_imputation_spatial,
    plot_task2_real_three_panel,
    prism_eval_and_save,
    run_clustering_eval_plot,
)
__all__ = [
    "AOTGraphConfig", "Cal_Spatial_Net", "PRISM", "PRISM_DM", "SMA_PAPER_METABOLITES",
    "Stats_Spatial_Net", "Transfer_pytorch_Data", "add_prism_interaction_pca",
    "align_cluster_to_reference", "align_cluster_to_truth", "annotate_sma_paper_metabolites",
    "aot_distance_matrix_full", "apply_interaction_embedding", "apply_magpie_landmarks_to_msi",
    "assign_dopamine_status", "attach_sma_metadata", "build_aligned_msi", "build_aot_knn_graph",
    "build_full_msi_with_missing", "build_modality_context_prior", "build_sma_new_label", "clustering",
    "compute_aot", "compute_covet", "compute_metrics_each_pair", "compute_similarity_prior",
    "covet_sqrt_to_aot_features", "estimate_magpie_affine", "evaluate", "evaluate_protein_prediction",
    "get_domain_label_order", "get_domain_palette", "get_missing_indices", "greedy_spatial_matching", "known_domain_presets",
    "load_checkpoint_state", "load_imputed_dopamine_predictions",
    "load_visium_rna_with_spatial", "materialize_prism_raw_imputation", "mclust_R", "pca",
    "plot_dopamine_distribution", "plot_imputation_metric_boxplot", "plot_magpie_alignment_preview",
    "plot_matching_summary_bar", "plot_pd_human_volcano", "plot_per_protein_correlations",
    "plot_prism_imputation_spatial", "plot_spatial_overlay", "plot_task2_real_three_panel",
    "prepare_similarity_subset", "prepare_sma_rna", "preprocess_adt", "preprocess_atac",
    "preprocess_metabolomics", "preprocess_omics", "preprocess_rna", "prism_eval_and_save",
    "register_domain_palette", "relabel_clusters_for_display", "run_clustering_eval_plot",
    "rewire_spatial_net",
    "run_imputed_dopamine_deg", "save_aot_matrix", "save_raw_layer_and_counts", "search_res",
    "select_best_device", "set_prism_plot_style", "set_seed", "show_real_missing",
    "simulate_celltype_missing", "simulate_missing_sliding", "sma_label_table", "spatial_mapping_table",
    "sparse_topk_global", "to_dense", "train_PRISM", "train_PRISM_DM", "transform_coordinates_affine",
    "write_sma_h5ad",
]
